name: CI

on:
  push:
    branches:
      - main
  workflow_dispatch:
  pull_request:
jobs:
  test:
    name: Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - uses: prefix-dev/setup-pixi@v0.9.0
      - run: pixi run test