name: CI

on:
  push:
    branches:
      - main
  workflow_dispatch:
  pull_request:

env:
  BUILD_EDITABLE_PYTHON: false

jobs:
  test:
    name: Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - name: Checkout repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
        with:
          submodules: recursive
      - uses: prefix-dev/setup-pixi@v0.9.0
        with:
          log-level: vv
          locked: false
      - run: pixi run test